file=$1
#open $file
sed -i 's/*//g' $file
sed -i 's/+//g' $file
sed -i 's/:1//g' $file
sed -i 's/:2//g' $file
sed -i 's/:3//g' $file
sed -i 's/         /\t/g' $file
sed -i 's/        /\t/g' $file
sed -i 's/       /\t/g' $file
sed -i 's/      /\t/g' $file
sed -i 's/     /\t/g' $file
sed -i 's/    /\t/g' $file
sed -i 's/   /\t/g' $file
sed -i 's/ /\t/g' $file
sed -i 's/\t\t/\t/g' $file
#awk -F "	" '{printf"%s\n",$3'} $file > predicts
#newFile=$2.$file.prd
#paste $2 predicts > $newFile
